Nominal/OHE-endoding

In [2]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [28]:
df=pd.DataFrame({'color':['red','yellow','green','red', 'yellow']})
df

color
0     red
1  yellow
2   green
3     red
4  yellow

In [29]:
# Performing fit and transform
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['color']]).toarray()

In [30]:
encoded_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())


In [31]:
encoded_df

color_green  color_red  color_yellow
0          0.0        1.0           0.0
1          0.0        0.0           1.0
2          1.0        0.0           0.0
3          0.0        1.0           0.0
4          0.0        0.0           1.0

In [3]:
df2=pd.DataFrame({'color':['red','purple','yellow','red']})

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

encoder.fit_transform(df2[['color']])

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 2, 1])

In [14]:
encoder.transform([['red']])

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [15]:
encoder.transform([['purple']])

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

ORDINAL ENCODING

In [ ]:
# Creating dataframe
df3=pd.DataFrame({'color':['red','magenta','lavendar','red','beige']})

from sklearn.preprocessing import OrdinalEncoder

In [ ]:
encoder=OrdinalEncoder(categories=[['red','magenta','lavendar','beige']])

In [29]:
encoder.fit_transform(df3[['color']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [3.]])

TARGET GUIDED ORDINAL ENCODING

Practice on tip dataset

In [30]:
import seaborn as sns

In [40]:
dff=sns.load_dataset('tips')
dff

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [44]:
mean_bill=dff.groupby('time')['total_bill'].mean().to_dict()

C:\Users\HP\AppData\Local\Temp\ipykernel_21108\2608745437.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill=dff.groupby('time')['total_bill'].mean().to_dict()


In [45]:
dff['dinner_bill']=dff['time'].map(mean_bill)

In [46]:
dff[['time','dinner_bill']]

time dinner_bill
0    Dinner   20.797159
1    Dinner   20.797159
2    Dinner   20.797159
3    Dinner   20.797159
4    Dinner   20.797159
..      ...         ...
239  Dinner   20.797159
240  Dinner   20.797159
241  Dinner   20.797159
242  Dinner   20.797159
243  Dinner   20.797159

[244 rows x 2 columns]

In [47]:
dff

total_bill   tip     sex smoker   day    time  size dinner_bill
0         16.99  1.01  Female     No   Sun  Dinner     2   20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3   20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3   20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2   20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4   20.797159
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3   20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2   20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2   20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2   20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2   20.797159

[244 rows x 8 columns]